export const SEEDS: Record<string, string[]> = {
  greetings: [
    "hello",
    "hi",
    "good morning",
    "good evening",
    "good night",
    "how are you",
    "how do you do",
    "nice to meet you",
    "pleased to meet you",
    "see you",
    "goodbye",
    "bye",
    "take care",
    "welcome",
    "congratulations",
    "best wishes",
    "cheers",
    "have a nice day",
    "what's up",
    "long time no see",
    "how's it going",
    "good to see you",
    "glad to see you",
    "how have you been",
    "greetings",
    "salutations",
    "good afternoon",
    "it's a pleasure",
    "welcome back",
    "nice to see you",
  ],
  food: [
    "apple",
    "banana",
    "bread",
    "cheese",
    "chicken",
    "rice",
    "noodle",
    "soup",
    "fish",
    "pork",
    "beef",
    "egg",
    "butter",
    "milk",
    "coffee",
    "tea",
    "vegetable",
    "fruit",
    "salad",
    "sandwich",
    "pizza",
    "hamburger",
    "sushi",
    "noodle soup",
    "dumpling",
    "cake",
    "cookie",
    "ice cream",
    "yogurt",
    "seafood",
    "shrimp",
    "crab",
    "lobster",
    "oyster",
    "tofu",
    "mushroom",
    "onion",
    "garlic",
    "pepper",
    "salt",
  ],
  common_verbs: [
    "to be",
    "to have",
    "to do",
    "to say",
    "to go",
    "to get",
    "to make",
    "to know",
    "to think",
    "to take",
    "to see",
    "to come",
    "to want",
    "to use",
    "to find",
    "to give",
    "to tell",
    "to work",
    "to call",
    "to try",
    "to ask",
    "to need",
    "to feel",
    "to become",
    "to leave",
    "to put",
    "to mean",
    "to keep",
    "to let",
    "to begin",
  ],
};
